### ISSUE TITLE
Code is missing

### ISSUE THREAD

**Issue by pavan4** [KAIST-VCLAB/texturefusion#1]
Thank you for the code! 

Is the recent commit up to date? The code fails to compile at this place:

```
unresolved external symbol  renderCorrespondenceCUDA at Linking time in CUDACameraTrackingMultiResRGBD.cpp
```

I only see `extern "C" void renderCorrespondenceCUDA(unsigned int imageWidth, unsigned int imageHeight, float *output, CameraTrackingInput cameraTrackingInput, float* intrinsics, CameraTrackingParameters cameraTrackingIParameters, float* transform);` 

But no definition for this in code?  Am I missing something here? 

fyi, I am able to compile and run `voxelhashing`

**Comment by pavan4** [comment]
I commented out that piece and was able to move past the compilation step. Upon running the sample I get this error: 

`CUDASceneRepChunkGrid::create:386: out of memory.` I have an Nvidia 2070 GPU card. Any parameters to tweak to let me run the demo with `fountain_all` data? 

Did anyone have luck running this?

**Comment by HulkMaker** [comment]
> I commented out that piece and was able to move past the compilation step. Upon running the sample I get this error:
> 
> `CUDASceneRepChunkGrid::create:386: out of memory.` I have an Nvidia 2070 GPU card. Any parameters to tweak to let me run the demo with `fountain_all` data?
> 
> Did anyone have luck running this?

Hi, Did you figure out this issue?

**Comment by pavan4** [comment]
Yes, I was able to run the demo by setting these parameters: 


This got rid of `CUDASceneRepChunkGrid` OOM error
```
s_hashNumBuckets = 50000;			
s_hashNumSDFBlocks = 50000;	
```

However, I am getting an OOM error`CUDASceneRepHashSDF` with this https://github.com/KAIST-VCLAB/texturefusion/blob/22dd0eef639e9b00179867cbedeec4c72b95ef98/Source/CUDASceneRepHashSDF.h#L198

So I had to also set 
```
s_offlineProcessing = false;
```

**Comment by chunduri11** [comment]
@pavan4 
Is it possible to setup and run the texturefusion code on Ubuntu pc with 2080ti gpu.

I am looking to setup the code, your suggestion on hardware and OS requirements will be very helpful.

Thanks

**Comment by pavan4** [comment]
> @pavan4
> Is it possible to setup and run the texturefusion code on Ubuntu pc with 2080ti gpu.
> 
> I am looking to setup the code, your suggestion on hardware and OS requirements will be very helpful.
> 
> Thanks

It should work. I was able to run on RTX 2070

**Comment by chunduri11** [comment]
Hi @pavan4 
Thanks for the quick reply.

I have compiled the vowel hashing repo and will replace the source folder in voxelhashing cuda folder with the source folder from texture fusion repo.

Does this work straight away or are you facing issues while doing that.?


How is the quality of the result 3D volume on your own data with texture fusion?

Thanks

**Comment by pavan4** [comment]
@chunduri11 , yeah those are the steps to get going. However, I had to spend some time to get the project to compile. 

I made a PR here with the complete project integrated with voxel hashing : https://github.com/KAIST-VCLAB/texturefusion/pull/3 which should be quite straight forward to build 

The quality of the result on my own data was not great or at least equivalent to the output of the dataset. The code still needs a major bit of work in terms of optimisation.

**Comment by chunduri11** [comment]
Hi @pavan4, thanks for the reply and the inputs. Very useful.

I am new to 3D reconstruction and also c++, your inputs are very helpful to me.

I am trying to compile your refactored code. I am facing errors related to NuiApi.h and NuiSkeleton.h.
From my exploration I see that these files are related to Kinect sdk 1.8, but I am using Kinect sdk 2.0 and corresponding runtime drivers.
Does ur refactored code work with Kinect sdk 2.0 with its runtime drivers or should I use Kinect sdk 1.8?

Thanks again.

**Comment by chunduri11** [comment]
@pavan4 
I have managed to compile the refactored code that you shared.

After compiling, when I run the code with the waterfall dataset, I am running into an error after reading the rib and depth images. 

**The error is as follows:
"DX11RGBDRenderer.h(132) : cudaSafeCall() Runtime API error 101: decompressing frame invalid device ordinal."**

Ever after this error message decompressing frame continues till 9 and stops execution.

Can you please help me in what is going wrong and how I can resolve this issue and ensure that I am able to generated 3D models for the waterfall dataset given in the repository?

Thanks

**Comment by CanCanZeng** [comment]
Hi, I'm trying to make your PR work, thank you for your modification! @pavan4 
I have a question, is it possible to save the textured mesh in the end? I'd like to save the reconstructed mesh result.
